PPO:
  batch_size: 32
  clip_range: 0.2
  ent_coef: 0.01
  gae_lambda: 0.95
  gamma: 0.99
  learning_rate: 0.0003
  max_grad_norm: 0.5
  n_epochs: 5
  n_steps: 1024
  vf_coef: 0.5
TRAINING:
  checkpoint_freq: 25000
  deterministic_eval: true
  eval_freq: 5000
  n_envs: 2
  n_eval_episodes: 5
  seed: 42
  total_timesteps: 50000
